---
abstract: 'Plugin of HTTP::MobileAgent for detecting smartphone'
author:
  - 'Masayuki Matsuki <y.songmu@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.36
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.04'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTTP-MobileAgent-Plugin-SmartPhone
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  HTTP::MobileAgent: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/Songmu/p5-HTTP-MobileAgent-Plugin-SmartPhone.git
version: 0.013
